---
- hosts: raspberry
  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      become: yes
  tasks:
    - name: Install additional packages
      apt:
        pkg:
        - python3-pip
        - docker-compose
        - docker.io
      become: yes
    - name: Alter user 'ubuntu' to allow access to 'docker'
      user:
        name: ubuntu
        shell: /bin/bash
        groups: docker
        append: yes
      become: yes
  post_tasks:
    - name: Rebooting
      reboot:
      become: yes


