---
- hosts: raspberry
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      become: yes
    - name: Install additional packages
      apt:
        pkg:
        - python3-pip
        - docker-compose
        - docker.io
      become: yes

