---
- hosts: raspberry
  become: yes
  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: true
  tasks:
    - name: Install additional packages
      apt:
        pkg:
        - python3-pip
        - docker-compose
        - docker.io
        state: present
    - name: Ensure user 'ubuntu' added to 'docker' group
      user:
        name: ubuntu
        groups: docker
        append: true
    - name: Ensure docker daemon is enabled
      service:
        name: docker
        enabled: yes
  post_tasks:
    - name: Rebooting
      reboot:
    - name: Check current docker-compose version.
      command: docker-compose --version
      register: docker_compose_current_version
      changed_when: false
      failed_when: false
    - debug:
        var: docker_compose_current_version
