---
- name: Ensure 'Heimdall' docker image pulled
  docker_image:
    name: "{{ heimdall_docker_image }}"
    source: pull
- name: Ensure 'Heimdall' container is running
  docker_container:
    name: heimdall
    state: started
    restart: yes
    restart_policy: unless-stopped
    init: yes
    image: "{{ heimdall_docker_image }}"
    # user: "{{ uid }}:{{ gid }}"
    ports:
      - 80:80
      - 443:443
    env:
      TZ: Europe/Berlin
      PUID: "{{ uid | quote }}"
      PGID: "{{ gid | quote }}"
    volumes:
      - "{{heimdall_config_dir}}:/config"
- name: Wait for init
  pause:
    minutes: 1
